/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.PasswordEntry;
import Model.User;
import Singletons.Controller;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Omnix
 */
public class InsertForm extends javax.swing.JFrame {

    private User u;
    private PasswordEntry pe;

    /**
     * Creates new form InsertForm
     */
    public InsertForm() {
        initComponents();
    }

    public InsertForm(User u) {
        this.u = u;
        initComponents();
    }

    public InsertForm(User u, PasswordEntry pe) {
        this.pe = pe;
        this.u = u;
        initComponents();
        txtPassword.setEnabled(false);
        txtService.setText(pe.getService());
        txtUsername.setText(pe.getUsername());
        txtPassword.setText(pe.getPassword());
        txtPassword.setEchoChar((char) 0);
        txtDescription.setText(pe.getDescription());
        btnShow.setVisible(false);
        btnInsert.setText("Update");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnInsert = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtService = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jLabel3.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        jLabel4.setText("Service:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtService)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnShow)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnShow)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        String btnText = btnShow.getText();

        if (btnText.equals("Show")) {
            txtPassword.setEchoChar((char) 0);
            btnShow.setText("Hide");
        } else {
            txtPassword.setEchoChar('*');
            btnShow.setText("Show");
        }

    }//GEN-LAST:event_btnShowActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if (pe == null) {
            String service = txtService.getText().trim();
            String username = txtUsername.getText().trim();
            String password = String.valueOf(txtPassword.getPassword());
            String description = txtDescription.getText().trim();

            txtService.setBackground(Color.white);
            txtUsername.setBackground(Color.white);
            txtPassword.setBackground(Color.white);
            txtDescription.setBackground(Color.white);

            if (service.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Service mustn't be empty.", "Service is too short", JOptionPane.ERROR_MESSAGE);
                txtService.setBackground(Color.red);
                return;
            }

            if (username.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username mustn't be empty.", "Username is too short", JOptionPane.ERROR_MESSAGE);
                txtUsername.setBackground(Color.red);
                return;
            }

            if (password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password mustn't be empty.", "Password is too short", JOptionPane.ERROR_MESSAGE);
                txtPassword.setBackground(Color.red);
                return;
            }

            PasswordEntry pe = new PasswordEntry();
            pe.setService(service);
            pe.setUsername(username);
            pe.setPassword(password);
            pe.setUserId(u.getId());
            pe.setDescription(description);
            boolean success = Controller.getInstance().insertEntry(pe, u);

            if (success) {
                JOptionPane.showMessageDialog(this, "Good job, you've saved an entry.", "Success", JOptionPane.INFORMATION_MESSAGE);
                Controller.getInstance().getMf().refreshEntryList();
                Controller.getInstance().getMf().refreshTable(Controller.getInstance().getMf().getEntryList());
                Controller.getInstance().getMf().loadCombobox();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "There was an error while communicating with the database.", "Failure", JOptionPane.ERROR_MESSAGE);
            }
        } else {

            if (txtService.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Service mustn't be empty.", "Service is too short", JOptionPane.ERROR_MESSAGE);
                txtService.setBackground(Color.red);
                return;
            }

            if (txtUsername.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username mustn't be empty.", "Username is too short", JOptionPane.ERROR_MESSAGE);
                txtUsername.setBackground(Color.red);
                return;
            }

            pe.setService(txtService.getText());
            pe.setUsername(txtUsername.getText());
            pe.setDescription(txtDescription.getText());
            boolean updated = Controller.getInstance().updateEntry(pe, u);

            if (updated) {
                JOptionPane.showMessageDialog(this, "Good job, you've updated an entry.", "Success", JOptionPane.INFORMATION_MESSAGE);
                Controller.getInstance().getMf().refreshEntryList();
                Controller.getInstance().getMf().refreshTable(Controller.getInstance().getMf().getEntryList());
                Controller.getInstance().getMf().loadCombobox();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "There was an error while communicating with the database.", "Failure", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtService;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
