/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import MFA.EmailService;
import MFA.OtpCode;
import MFA.OtpGenerationResult;
import MFA.OtpService;
import MFA.OtpVerificationResult;
import Model.User;
import Singletons.Controller;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Omnix
 */
public class LoginForm extends javax.swing.JFrame {

    private static final String EMAIL_PATTERN = "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$";
    private static final int OTP_TIMER_SECONDS = (int) OtpService.VALIDITY_DURATION.getSeconds();
    private final OtpService otpService = new OtpService();
    private final EmailService emailService = new EmailService();
    private OtpCode currentOtp;
    private User pendingMfaUser;
    private Timer otpTimer;
    private int otpSecondsRemaining;

    /**
     * Creates new form RegistrationForm
     */
    public LoginForm() {
        initComponents();
        resetOtpState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtOtp = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnSendCode = new javax.swing.JButton();
        lblOtpTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email");

        jLabel2.setText("Password");

        jLabel3.setText("OTP");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnSendCode.setText("Send code");
        btnSendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendCodeActionPerformed(evt);
            }
        });

        lblOtpTimer.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txtPassword)
                    .addComponent(txtOtp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSendCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOtpTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnShow))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOtpTimer)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        String btnText = btnShow.getText();

        if (btnText.equals("Show")) {
            txtPassword.setEchoChar((char) 0);
            btnShow.setText("Hide");
        } else {
            txtPassword.setEchoChar('*');
            btnShow.setText("Show");
        }

    }//GEN-LAST:event_btnShowActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        User u = authenticateCredentials();

        if (u == null) {
            return;
        }

        if (!verifyOtpBeforeLogin(u)) {
            return;
        }

        completeLogin(u);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        RegistrationForm rf = new RegistrationForm();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnSendCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendCodeActionPerformed
        User u = authenticateCredentials();

        if (u == null) {
            return;
        }

        try {
            OtpGenerationResult result = otpService.createOtp(u.getId(), currentOtp);
            emailService.sendOtpCode(u.getEmail(), result.getPlainCode());
            currentOtp = result.getOtpCode();
            pendingMfaUser = u;
            txtOtp.setText("");
            txtOtp.setEnabled(true);
            startOtpTimer();
            JOptionPane.showMessageDialog(this, "Verification code sent to your email.", "OTP sent", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to send verification code.", "Email problem", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSendCodeActionPerformed

    private User authenticateCredentials() {
        String email = txtUsername.getText().trim();
        String password = String.valueOf(txtPassword.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter both credentials!", "Entry error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Enter a valid email address.", "Invalid email", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        User u = Controller.getInstance().loginUser(email, password);

        if (u.getId() < 0) {
            JOptionPane.showMessageDialog(this, "Wrong credentials.", "Login unsuccessful", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return u;
    }

    private boolean verifyOtpBeforeLogin(User user) {
        String submittedCode = txtOtp.getText().trim();

        if (currentOtp == null || pendingMfaUser == null || pendingMfaUser.getId() != user.getId()) {
            JOptionPane.showMessageDialog(this, "Send a verification code first.", "OTP required", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        OtpVerificationResult result = otpService.verify(currentOtp, submittedCode);
        if (result.isSuccessful()) {
            stopOtpTimer();
            return true;
        }

        showOtpFailure(result.getStatus());
        updateOtpTimerLabel();
        return false;
    }

    private void showOtpFailure(OtpVerificationResult.Status status) {
        switch (status) {
            case INVALID_INPUT:
                JOptionPane.showMessageDialog(this, "Enter the 6-digit verification code.", "Invalid OTP", JOptionPane.ERROR_MESSAGE);
                break;
            case EXPIRED:
                JOptionPane.showMessageDialog(this, "Verification code expired. Send a new code.", "OTP expired", JOptionPane.ERROR_MESSAGE);
                break;
            case TOO_MANY_ATTEMPTS:
                JOptionPane.showMessageDialog(this, "Too many wrong attempts. Send a new code.", "OTP locked", JOptionPane.ERROR_MESSAGE);
                break;
            case CONSUMED:
                JOptionPane.showMessageDialog(this, "Verification code was already used. Send a new code.", "OTP used", JOptionPane.ERROR_MESSAGE);
                break;
            case INVALID_CODE:
            default:
                JOptionPane.showMessageDialog(this, "Wrong verification code.", "Invalid OTP", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }

    private void completeLogin(User user) {
        JOptionPane.showMessageDialog(this, "You've successully logged in.", "Login successful", JOptionPane.INFORMATION_MESSAGE);
        MainForm mf = new MainForm(user);
        mf.setVisible(true);
        this.dispose();
    }

    private void resetOtpState() {
        currentOtp = null;
        pendingMfaUser = null;
        txtOtp.setText("");
        txtOtp.setEnabled(true);
        lblOtpTimer.setText(" ");
    }

    private void startOtpTimer() {
        stopOtpTimer();
        otpSecondsRemaining = OTP_TIMER_SECONDS;
        updateOtpTimerLabel();
        otpTimer = new Timer(1000, event -> {
            otpSecondsRemaining--;
            if (otpSecondsRemaining <= 0) {
                stopOtpTimer();
                if (currentOtp != null && !currentOtp.isConsumed()) {
                    currentOtp.markConsumed();
                }
                lblOtpTimer.setText("Code expired.");
            } else {
                updateOtpTimerLabel();
            }
        });
        otpTimer.start();
    }

    private void stopOtpTimer() {
        if (otpTimer != null) {
            otpTimer.stop();
            otpTimer = null;
        }
    }

    private void updateOtpTimerLabel() {
        if (currentOtp == null) {
            lblOtpTimer.setText(" ");
            return;
        }

        if (currentOtp.isConsumed()) {
            lblOtpTimer.setText("Code inactive.");
            return;
        }

        lblOtpTimer.setText("Code expires in " + otpSecondsRemaining + "s.");
    }

    private boolean isValidEmail(String email) {
        return email != null && email.matches(EMAIL_PATTERN);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSendCode;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblOtpTimer;
    private javax.swing.JTextField txtOtp;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
